// ⚠️ ไฟล์นี้ถูกสร้างอัตโนมัติโดย scripts/gen-endpoints.mjs — ห้ามแก้มือ
// ที่มาของรายชื่อ: `get("list") === "…"` ในซอร์สของ netlify/functions/core.mjs (แหล่งเดียว)
// 🚫 ห้ามเอาไปใช้ตัดสินว่าเส้นไหนเปิด/ปิด — ใช้เขียนข้อความบอกทาง และให้ด่านฝั่งจอเทียบเท่านั้น
export const generatedAt = "2026-09-25T06:43:42.328Z";
export const source = "netlify/functions/core.mjs (get(\"list\") === \"…\")";
export const lists = [
 "branches",
 "bundleitems",
 "bundles",
 "categories",
 "channel-gaps",
 "contacts",
 "deadstock",
 "logistics",
 "missing-sku",
 "moves",
 "orderfacets",
 "orders",
 "poscats",
 "purchaseitems",
 "purchases",
 "quotations",
 "returnorders",
 "returns-inbox",
 "sales",
 "stock",
 "stockcard",
 "topproducts",
 "transfers",
 "warehouses"
];
// ⚠️ กองนี้ **หยาบกว่า** lists — มาจาก `if (url.searchParams.get("xxx"))` ซึ่งปนกับตัวกรองได้
//    ใช้เป็น 'รายการที่ต้องดูด้วยตา' ห้ามนับเป็นจำนวนเส้นที่แน่นอน
export const paramRoutes = [
 "addbundle",
 "addcontact",
 "addpo",
 "addproduct",
 "addquotation",
 "addreturn",
 "addsale",
 "appliedkeys",
 "arch",
 "archiveslips",
 "backup",
 "backupstatus",
 "batch",
 "blankwhere",
 "blocked",
 "bundleitems",
 "cardguess",
 "categoryvalues",
 "channelcompare",
 "clearpolicyerrors",
 "connections",
 "crontable",
 "customer",
 "d1move",
 "daily",
 "dbinfo",
 "deleteproduct",
 "deploys",
 "doccoverage",
 "dupsku",
 "endpoints",
 "envcheck",
 "imgmirror",
 "init",
 "jobtiming",
 "links",
 "mkpfees",
 "mkpfeesum",
 "mkpfeesync",
 "mkpfinance",
 "mkpfinancemirror",
 "mkpfinanceprobe",
 "mkpfinancesync",
 "monthly",
 "move",
 "movedel",
 "noitems",
 "ordercheck",
 "orderitems",
 "peak",
 "pending",
 "pendingsplit",
 "poslookup",
 "productimage",
 "productlabels",
 "purchase",
 "pushledgerbackfill",
 "pushstate",
 "pushstuck",
 "pushsweep",
 "quotation",
 "quotedit",
 "recon",
 "registry",
 "registryrows",
 "reorder",
 "resettransfers",
 "restore",
 "return",
 "returnorder",
 "returnphoto",
 "returnskus",
 "sale",
 "saledel",
 "salevoid",
 "shopeesync",
 "shopeeunlisted",
 "shopinfo",
 "skuaudit",
 "slip",
 "slips",
 "slipsarchive",
 "slipscan",
 "snapshot",
 "statuscross",
 "stock",
 "stockcompare",
 "stockpush",
 "stockpushguards",
 "stockpushlive",
 "stockpushlog",
 "stockpushverify",
 "stockwriteprobe",
 "sweepnow",
 "sweeptiming",
 "sync",
 "syncbundlerecipes",
 "syncbundles",
 "synccontacts",
 "synccontactsnow",
 "syncproducts",
 "syncpurchases",
 "syncreturns",
 "synctransfers",
 "tiktokshape",
 "tiktokstock",
 "tiktoksync",
 "tokens",
 "transfer",
 "updateproduct",
 "uploadtoken",
 "usage",
 "warehousevalues",
 "warnkeys",
 "zortarch",
 "zortarchived",
 "zortbundle",
 "zortclaims",
 "zortcostfields",
 "zortdoccounts",
 "zortdocfilter",
 "zortdocrows",
 "zortdocs",
 "zortfields",
 "zortfiles",
 "zortlist",
 "zortmissing",
 "zortmonthly",
 "zortnoapi",
 "zortone",
 "zortpo",
 "zortpoid",
 "zortproduct",
 "zortproductfields",
 "zortwarehouse",
 "zortwebhook"
];
// 🏷️ ป้าย อ่าน/เขียน ต่อเส้น — คิดจาก **การตรวจ method ในซอร์สจริง** ไม่ใช่จากชื่อ
//    write = บังคับ POST · readonly = บังคับ GET · unknown = ไม่มีการตรวจ method เลย
// 🚫 **unknown ไม่ใช่ readonly** — ห้ามยิงสำรวจเส้น unknown โดยไม่อ่านซอร์สก่อน
//    (ฝั่งจอเกือบยิง `saledel` ซึ่งลบใบขายจริง เพราะแยกกองด้วยคำนำหน้าชื่อ 19 ก.ย. 2569)
export const routeMethod = {
 "registry": "unknown",
 "registryrows": "write",
 "d1move": "unknown",
 "stockpushlive": "write",
 "pushsweep": "write",
 "pushledgerbackfill": "write",
 "skuaudit": "readonly",
 "sweeptiming": "write",
 "jobtiming": "readonly",
 "pushstate": "unknown",
 "dupsku": "unknown",
 "endpoints": "readonly",
 "crontable": "unknown",
 "deploys": "readonly",
 "appliedkeys": "readonly",
 "warnkeys": "readonly",
 "pushstuck": "readonly",
 "stockpushlog": "unknown",
 "stockpushguards": "unknown",
 "stockwriteprobe": "readonly",
 "stockpushverify": "unknown",
 "stockpush": "unknown",
 "imgmirror": "write",
 "mkpfinanceprobe": "readonly",
 "mkpfinance": "readonly",
 "mkpfinancemirror": "readonly",
 "mkpfinancesync": "write",
 "mkpfees": "readonly",
 "mkpfeesync": "write",
 "mkpfeesum": "readonly",
 "dbinfo": "readonly",
 "init": "unknown",
 "movedel": "write",
 "addproduct": "write",
 "updateproduct": "write",
 "deleteproduct": "write",
 "envcheck": "readonly",
 "zortproductfields": "unknown",
 "zortproduct": "readonly",
 "zortpo": "readonly",
 "zortpoid": "readonly",
 "zortlist": "readonly",
 "archiveslips": "write",
 "slipscan": "readonly",
 "slipsarchive": "readonly",
 "slips": "readonly",
 "slip": "readonly",
 "zortfiles": "readonly",
 "zortbundle": "readonly",
 "productlabels": "readonly",
 "productimage": "write",
 "addpo": "write",
 "batch": "write",
 "addsale": "write",
 "addcontact": "write",
 "addbundle": "write",
 "shopinfo": "unknown",
 "addquotation": "write",
 "addreturn": "write",
 "quotedit": "write",
 "zortclaims": "unknown",
 "zortarch": "unknown",
 "zortnoapi": "unknown",
 "zortwebhook": "unknown",
 "doccoverage": "readonly",
 "returnskus": "unknown",
 "quotation": "unknown",
 "zortdocrows": "readonly",
 "zortdocs": "unknown",
 "sweepnow": "unknown",
 "clearpolicyerrors": "unknown",
 "move": "write",
 "returnphoto": "unknown",
 "return": "write",
 "saledel": "write",
 "salevoid": "write",
 "sale": "write",
 "backupstatus": "unknown",
 "backup": "unknown",
 "restore": "unknown",
 "arch": "unknown",
 "uploadtoken": "unknown",
 "warehousevalues": "write",
 "categoryvalues": "write",
 "bundleitems": "write",
 "syncbundles": "unknown",
 "syncbundlerecipes": "unknown",
 "blocked": "unknown",
 "zortarchived": "readonly",
 "zortmissing": "readonly",
 "zortdocfilter": "readonly",
 "zortcostfields": "readonly",
 "zortwarehouse": "unknown",
 "links": "unknown",
 "reorder": "unknown",
 "syncproducts": "unknown",
 "syncpurchases": "unknown",
 "usage": "unknown",
 "purchase": "unknown",
 "connections": "unknown",
 "customer": "unknown",
 "synccontactsnow": "unknown",
 "synccontacts": "unknown",
 "transfer": "unknown",
 "syncreturns": "unknown",
 "resettransfers": "unknown",
 "synctransfers": "unknown",
 "poslookup": "unknown",
 "orderitems": "readonly",
 "noitems": "readonly",
 "peak": "unknown",
 "sync": "unknown",
 "recon": "readonly",
 "shopeesync": "unknown",
 "tiktoksync": "unknown",
 "tiktokshape": "readonly",
 "tiktokstock": "readonly",
 "zortdoccounts": "readonly",
 "ordercheck": "readonly",
 "tokens": "unknown",
 "daily": "unknown",
 "monthly": "unknown",
 "returnorder": "unknown",
 "zortmonthly": "unknown",
 "pending": "unknown",
 "cardguess": "readonly",
 "blankwhere": "readonly",
 "statuscross": "readonly",
 "pendingsplit": "readonly",
 "zortone": "readonly",
 "zortfields": "readonly",
 "channelcompare": "readonly",
 "stockcompare": "readonly",
 "shopeeunlisted": "unknown",
 "snapshot": "unknown",
 "stock": "unknown"
};
// ⚠️ ช่องที่ตัวเขียนของ ZORT รับเข้า — **หยาบ** (regex เก็บ o.xxx) ใช้ดูด้วยตา ห้ามถือเป็นสัญญา API
export const writeFields = {
 "zortAddProduct": [
  "barcode",
  "category",
  "confirm",
  "description",
  "name",
  "productType",
  "ref",
  "sku",
  "stock",
  "tags",
  "unit"
 ],
 "zortAddSale": [
  "address",
  "channel",
  "cod",
  "confirm",
  "customer",
  "day",
  "discount",
  "items",
  "note",
  "number",
  "paid",
  "paymentMethod",
  "phone",
  "ref",
  "shipping",
  "status",
  "warehouse"
 ],
 "zortAddBundle": [
  "confirm",
  "items",
  "name",
  "price",
  "ref",
  "sku",
  "vat"
 ],
 "zortAddWarehouse": [
  "address",
  "code",
  "confirm",
  "name",
  "ref"
 ],
 "zortAddContact": [
  "code",
  "confirm",
  "email",
  "idnumber",
  "name",
  "ref",
  "taxId"
 ],
 "zortUpdateProduct": [
  "confirm",
  "id",
  "ref",
  "sku",
  "vat"
 ],
 "zortDeleteProduct": [
  "confirm",
  "id",
  "ref",
  "sku"
 ],
 "zortUpdateProductImage": [
  "confirm",
  "id",
  "image",
  "ref",
  "sku"
 ],
 "zortAddQuotations": [
  "confirm",
  "rows"
 ],
 "zortBatch": [
  "confirm",
  "rows"
 ],
 "zortOrderShipping": [
  "confirm",
  "id",
  "ref",
  "shippingChannel",
  "shippingDate",
  "shippingchannel",
  "shippingdate",
  "trackingNo",
  "trackingno"
 ],
 "zortOrderShippingBatch": [
  "confirm",
  "rows"
 ],
 "zortReceivePurchaseOrder": [
  "confirm",
  "date",
  "id",
  "items",
  "ref",
  "warehouse"
 ],
 "zortAddReturnPurchaseOrder": [
  "confirm",
  "day",
  "discount",
  "items",
  "note",
  "number",
  "paid",
  "paymentMethod",
  "poId",
  "ref",
  "shipping",
  "status",
  "vendor",
  "vendorCode",
  "warehouse"
 ],
 "zortVoidPurchaseOrder": [
  "confirm",
  "id",
  "number",
  "ref"
 ],
 "zortAddReturnOrder": [
  "confirm",
  "customer",
  "items",
  "note",
  "ref",
  "reference",
  "vendor"
 ],
 "zortAddPurchaseOrder": [
  "confirm",
  "items",
  "note",
  "paid",
  "paymentMethod",
  "ref",
  "status",
  "vendor"
 ],
 "zortAddQuotation": [
  "confirm",
  "customer",
  "items",
  "note",
  "phone",
  "ref",
  "reference"
 ],
 "zortEditQuotation": [
  "confirm",
  "customer",
  "id",
  "items"
 ],
 "zortVoidQuotation": [
  "confirm",
  "id"
 ],
 "zortDocCoverage": [
  "id",
  "number"
 ]
};
